language: node_js
node_js:
- '8'
env:
  global:
  - GH_USER_EMAIL="travis@example.org"
  - GH_USER_NAME="cozy-bot"
  - DEPLOY_REPOSITORY="git@github.com:konnectors/cozy-konnector-ameli.git"
  matrix:
  - secure: WGDv0ZfknIO7SIgT+eiaKn8i7U7kvN3mG9eYvPeHBK64mC6pqMwYsWLEWTD1y3y5z/fz99yFRWXzgl+J+zq2RfkhmD2aEg/Dv1ZuTpPVgvQwG/Hpie37xxUcM3gghh+2nR4pPAqYgC9LLTLlz7SaKHexBEuE644PWvZuHTGzk8ybV53xbWJtHTHxE95RI1Qwp1Qz+lUHOd4VZLPS1Q0bCV6uaL31SeXEW8z3o/Jsgh0g11JfX27mg6bJC3h5TGndfkoxynXp9jlc95GTIRebc4R7/rnNcMPgFb4hyvKFjCiRyY1u/p/pexlwqxJ/UogjixXkz9QDd4xhC2Oi3NNdRg/lDBodwzl6Ro8Jpv7XE764q3mVq00YTHN1exAXgoNBSjfXzkV0jJ9prPZ3oh61KLmuKW6PuyFleeW+1Y28VhCemZx99eUWKtRsB+yDtj3Aq180kYdMlR4JLHNRC2gan60wbM4GuvgzvX5mVeEbig4WUloXvWoeYxUDXfP5lhLk7Suv3+i36lP1+KMTFDktKV2EI9MPqhaoTAGzUOoiQBSp8OFIkPVqYXx7pSBKHPGNnH5XFgW0FbyqO+kXDs+Gl5uv8QZFBubB6/hTnNiFimydybveJhWMv3Mq7aGpmGW9lEODAnrRcLfde7UVJScayx3JgIM/xtF5D4Ddnj7fjr8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - latest
script:
- yarn lint
- yarn build
- if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy
  # script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=latest yarn deploy
  on:
    branch: prod
# - provider: script
#   skip-cleanup: true
#   script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
#   on:
#     tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_5e5225ed2e56_key -iv $encrypted_5e5225ed2e56_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
