language: node_js
node_js:
  - '8'
env:
  global:
    # kosssi GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=$GITHUB_TOKEN -r konnectors/cozy-konnector-ameli
    - secure: "lrH+D8jaU/rZ7MMYcnVO+oU725Ag46hS65B/VCI8MORnSRRwJqVblSF0LbTYxfIscLPTOuI54QscChOrzkCsIDHdis5PO2o18Un3d6bUF+CrFRwGOFgTOnEKdS6uN6wBUpea9CRe4XS66KOVHlVchbmu3MlLWgSr08j5ikeF0d3uupgH3HpSZbi4vMcaxLbBxgdfDiAX72jeXb1VnCYA+BCaPhVBRKaO0DIzJAeYBF50gJ9/giZm10lr581bSo3sScKaYA4+Njbl9otgWSvnUMZWP+cVjTwmRU6JUzH1wBMiaeeoSzqNCbn/q1H/wL+pdks+8LpwA4e8niTaWkGElDf56TyTHvklYADhYuxkDjpC6+Pgp3P95WPflNo0wQVTZ4CPLGvAn85oZnRh21m5dn2hZvxFojEYbAvgkWrGuSydyPH6ar/7XQfXtpvJy9icvoOOhwOKIwt3h4PAlxQRd6BqJvl0oPXNt3q14ORE852N5z37M+AilrSU/Wqr0ZSneanXWBbTj8qThLeAo9TZnieIqdsc2IHhrf1dRaUu0NGlKLGX5b/Fesawc6kXJ67fqbEjr0hTppV3MoPg9bjzHklEEZE1YnUZMxsrYOffxbqBUKJ6aMLtCxgfX3QE1bFqNyk5ZkV7yIQuDGMTGAuIi5iIRsfeRaY3ljn00ZiH6YQ="
  matrix:
    # kosssi account
    - secure: MhE6co+33V7zAChGxZMowpsNBpEDc5bA9STbqqSINCuzWpYF5I2u/4NMqqOK2SWhUmrW/B7yazdlvLM4+UT2OHfn11Jw8+sX1szkn6JoD5o1nNrI1rITx+4MLBEDFgs8FXiaTeg785d7b7i85PubikyaQYiSW7wRyoChcCFD6BLzw84CZHeGdD9XyKMwVuWps2ZzP6XijP5s6UD1ex9g8rCuqGjqrlESMQ7DBWT4DaQKGfAp3iF1LIjELBDyuLllwSMTgYvrwRueti7kO4LnnXaYMTLcyppr2Ztl3dtocsTvnaoff/XvwK1CfRnnW9G/a6ZilKrBEJ9NvWmPwNe4qbCBMcAb9c4GqJHWnRyCV8rOZYnrpS3w/IMrOeodr2ZZp6oQULFHCXXFSWU6DSeeZltmREeAMCw6gi30UO9ikaoo5m18wLDbs969A8v3VlXEyDzf4bx4MLtNPXBNEChZhQTmzLrBiTYLOKFL42nnSfRqCqu7yZ3AWdz9shgowK40DF2GhD+zSoRdRZst9TBnI/zjkzl11G+/71SptgYDNjmHFbzprQEydLal4pdzpztSAnz/lP9fePsw7Nx4zo5x8+XUuKx4N7JqdPEguSgP5bmFxcwwDvks2d1SZTy683lqtsCKr71iEzhKjpLZle6rIjYCdT7emPraYOZXRnSDnzA=
    # doubleface account
    - secure: WGDv0ZfknIO7SIgT+eiaKn8i7U7kvN3mG9eYvPeHBK64mC6pqMwYsWLEWTD1y3y5z/fz99yFRWXzgl+J+zq2RfkhmD2aEg/Dv1ZuTpPVgvQwG/Hpie37xxUcM3gghh+2nR4pPAqYgC9LLTLlz7SaKHexBEuE644PWvZuHTGzk8ybV53xbWJtHTHxE95RI1Qwp1Qz+lUHOd4VZLPS1Q0bCV6uaL31SeXEW8z3o/Jsgh0g11JfX27mg6bJC3h5TGndfkoxynXp9jlc95GTIRebc4R7/rnNcMPgFb4hyvKFjCiRyY1u/p/pexlwqxJ/UogjixXkz9QDd4xhC2Oi3NNdRg/lDBodwzl6Ro8Jpv7XE764q3mVq00YTHN1exAXgoNBSjfXzkV0jJ9prPZ3oh61KLmuKW6PuyFleeW+1Y28VhCemZx99eUWKtRsB+yDtj3Aq180kYdMlR4JLHNRC2gan60wbM4GuvgzvX5mVeEbig4WUloXvWoeYxUDXfP5lhLk7Suv3+i36lP1+KMTFDktKV2EI9MPqhaoTAGzUOoiQBSp8OFIkPVqYXx7pSBKHPGNnH5XFgW0FbyqO+kXDs+Gl5uv8QZFBubB6/hTnNiFimydybveJhWMv3Mq7aGpmGW9lEODAnrRcLfde7UVJScayx3JgIM/xtF5D4Ddnj7fjr8=
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
  - if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-ameli
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-ameli
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
